# Cross build the Rust application using musl target on aarch64, x86_64 and mipsel, then publish them in the release.
name: Build and Publish
on:
  # Run on each pull requests
  pull_request:
  push:
    # Run on each push to master
    branches: [master]
  # Run on release is published
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [aarch64, x86_64, mipsel]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install cross
        run: cargo install cross
      - name: Build using cross
        run: cross build --target ${{ matrix.target }}-unknown-linux-musl --release
      - name: Upload as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}Re
        # Run only if a release is published
        if: github.event_name == 'release'
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/${{ matrix.target }}-unknown-linux-musl/release/cron-run
          asset_name: cron-run.${{ matrix.target }}
          asset_content_type: application/octet-stream
